### ISSUE TITLE
💡 [REQUEST] - Issue tracker

### ISSUE THREAD

**Issue by ciscoLegrand** [CreadixGal/aeksion#101]
### Start Date

01/31/2023

### Implementation PR
101-request-issue-tracker](url)

### Reference Issues

#101

### Summary

Add A Issue tracker where client could explain and upload image of requireds enhancements and problems.

### Basic Example

- [x] add a section in the aside menu or similar for issue tracker.

- [x] when clicked on issue tracker show a form where can explain a problem or describe a new feature 

- [x] can add images on the form to has a better explanations of the problem or feature

### Drawbacks

#
